FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONPATH=/srv/sap/app

WORKDIR /srv/sap

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
      imagemagick \
      curl \
      tesseract-ocr \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY app ./app

CMD ["sh", "-c", "uvicorn app.processing_service.app:app --host ${API_HOST:-0.0.0.0} --port ${API_PORT:-8001}"]
